version: "2"

output:
  formats:
    text:
      colors: true

# TODO: "go fix" -- what is it?  What does it do?

linters:
  default: none
  enable:
    - depguard
    - errcheck
    - errorlint
    - godox
    - govet
    - ineffassign
    - lll
    - nolintlint
    - sqlclosecheck
    - staticcheck
    - unused
    - whitespace
    - wrapcheck

    # To add later:
    # - dupl
    # - exhaustive
    # - exhaustruct
    # - forbidigo (println, etc)
    # - depguard (remove logrus)
    # - nakedret
    # - predeclared
    # - rowserrcheck: # Ensure Rows.Err is checked
    #     packages:
    #       - github.com/jmoiron/sqlx
    # - testpackage
    # - unparam

    # Investigate:
    # - gocritic
    # - gofumpt
    # - revive
    # - thelper

  # Useless linters:
  # - dogsled
  # - wsl  (don't like it for now)
  # - golint (deprecated, replaced by 'revive')

  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: io/ioutil
              desc: replace with the matching functions from `io` or `os` packages
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
    errcheck:
      # report about not checking of errors in type assertions: `a := b.(MyStruct)`;
      # default is false: such cases aren't reported by default.
      check-type-assertions: true
      # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
      # default is false: such cases aren't reported by default.
      check-blank: true
    errorlint:
      errorf: true      # Ensure Errorf only uses %w (not %v or %s etc) for errors
      asserts: true     # Require errors.As instead of type-asserting
      comparison: true  # Require errors.Is instead of equality-checking
    godox:
      # report any comments starting with keywords, this is useful for TODO or FIXME comments that
      # might be left in the code accidentally and should be resolved before merging
      keywords: # default keywords are TODO, BUG, and FIXME, these can be overwritten by this setting
        - XXX
    govet:
      disable:
        - fieldalignment
        - composites
        - shadow
      enable-all: true
    lll:
      line-length: 140
      tab-width: 4
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    staticcheck:
      go: "1.23"
      checks:
        - all
        - -QF1003
        - -QF1008 # TODO: remove this one
        - -ST1001
        - -ST1003
        - -ST1013
        - -ST1005 # TODO: remove this one
        - -ST1016 # TODO: remove this one
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - pkg/persistence/instrumented_query.go
      - cmd/twitter/autocomplete.go

formatters:
  enable:
    # - gci
    - gofmt
  settings:
    gci:
      sections:
        - prefix(testing)
        - standard
        - default
        - localmodule
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  uniq-by-line: false
