// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package webserver

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"

	"html/template"
)

func NavSidebar(go_tpl *template.Template, global_data PageGlobalData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<nav id=\"nav-sidebar\" class=\"nav-sidebar\" hx-trigger=\"load delay:3s\" hx-get=\"/nav-sidebar-poll-updates\" hx-swap=\"outerHTML\"><div id=\"logged-in-user-info\"><div class=\"button row\" hx-get=\"/login\" hx-trigger=\"click\" hx-target=\"body\" hx-push-url=\"true\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.FromGoHTML(go_tpl.Lookup("author-info"), global_data.ActiveUser).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<img class=\"svg-icon\" src=\"/static/icons/dotdotdot.svg\" width=\"24\" height=\"24\"></div></div><ul class=\"nav-sidebar__buttons\"><a href=\"/timeline\"><li class=\"button labelled-icon\"><img class=\"svg-icon\" src=\"/static/icons/home.svg\" width=\"24\" height=\"24\"> <label class=\"nav-sidebar__button-label\">Home</label></li></a> <a onclick=\"document.querySelector(&#39;#searchBar&#39;).focus()\"><li class=\"button labelled-icon\"><img class=\"svg-icon\" src=\"/static/icons/explore.svg\" width=\"24\" height=\"24\"> <label class=\"nav-sidebar__button-label\">Explore</label></li></a> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if global_data.ActiveUser.Handle != "[nobody]" {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a href=\"/notifications\"><li class=\"nav-sidebar__notifications button labelled-icon\"><img class=\"svg-icon\" src=\"/static/icons/notifications.svg\" width=\"24\" height=\"24\"> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if global_data.NotificationBubbles.NumRegularNotifications != 0 {
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<span class=\"nav-sidebar__notifications-count\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var2 string
				templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprint(global_data.NotificationBubbles.NumRegularNotifications))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/webserver/nav_sidebar.templ`, Line: 35, Col: 123}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</span> ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<label class=\"nav-sidebar__button-label\">Notifications</label></li></a> <a href=\"/messages\"><li class=\"nav-sidebar__messages button labelled-icon\"><img class=\"svg-icon\" src=\"/static/icons/messages.svg\" width=\"24\" height=\"24\"> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if global_data.NotificationBubbles.NumMessageNotifications != 0 {
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<span class=\"nav-sidebar__notifications-count\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprint(global_data.NotificationBubbles.NumMessageNotifications))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/webserver/nav_sidebar.templ`, Line: 44, Col: 123}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</span> ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<label class=\"nav-sidebar__button-label\">Messages</label></li></a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a href=\"/lists\"><li class=\"button labelled-icon\"><img class=\"svg-icon\" src=\"/static/icons/lists.svg\" width=\"24\" height=\"24\"> <label class=\"nav-sidebar__button-label\">Lists</label></li></a> <a href=\"/bookmarks\"><li class=\"button labelled-icon\"><img class=\"svg-icon\" src=\"/static/icons/bookmarks.svg\" width=\"24\" height=\"24\"> <label class=\"nav-sidebar__button-label\">Bookmarks</label></li></a> <a hx-get=\"/communities\"><li class=\"button labelled-icon\"><img class=\"svg-icon\" src=\"/static/icons/communities.svg\" width=\"24\" height=\"24\"> <label class=\"nav-sidebar__button-label\">Communities</label></li></a> <a href=\"#\"><li class=\"button labelled-icon\"><img class=\"svg-icon\" src=\"/static/icons/verified.svg\" width=\"24\" height=\"24\"> <label class=\"nav-sidebar__button-label\">Verified</label></li></a> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if global_data.ActiveUser.Handle != "[nobody]" {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 templ.SafeURL = templ.URL(fmt.Sprintf("/%s", global_data.ActiveUser.Handle))
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(string(templ_7745c5c3_Var4)))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"><li class=\"button labelled-icon\"><img class=\"svg-icon\" src=\"/static/icons/profile.svg\" width=\"24\" height=\"24\"> <label class=\"nav-sidebar__button-label\">Profile</label></li></a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a href=\"https://twitter.com\" target=\"_blank\"><li class=\"button labelled-icon\"><img class=\"svg-icon\" src=\"/static/icons/internet.svg\" width=\"24\" height=\"24\"> <label class=\"nav-sidebar__button-label\">Go online</label></li></a> <a href=\"#\"><li class=\"button labelled-icon\"><img class=\"svg-icon\" src=\"/static/icons/more.svg\" width=\"24\" height=\"24\"> <label class=\"nav-sidebar__button-label\">More</label></li></a></ul></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
