# https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/
# https://woodpecker-ci.org/docs/usage/volumes

steps:
  docker-build-go:
    image: docker
    commands:
      - cd .woodpecker/docker
      - docker build -f go.dockerfile -t offline-twitter/go .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  docker-build-go-mingw:
    image: docker
    commands:
      - cd .woodpecker/docker
      - docker build -f go-mingw.dockerfile -t offline-twitter/go-mingw .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  docker-build-innosetup:
    image: docker
    commands:
      - cd .woodpecker/docker
      - docker build -f innosetup.dockerfile -t offline-twitter/innosetup .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
