# https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/
# https://woodpecker-ci.org/docs/usage/volumes

pipeline:
  docker-go:
    image: docker
    commands:
      - cd .woodpecker/docker
      - docker build -f go.dockerfile -t offline-twitter/go .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
